#!/usr/bin/env python3
"""
analyze_plot.py - turn a TSN-FlexTest I226 measurement campaign into statistics
and figures.

Input : a results directory produced by run_measurement.sh, containing one
        subdirectory per measurement point with tx.csv, rx.csv and meta.json.
Output: summary.csv, summary.md and a set of PNG/PDF figures in <results>/figures/.

One-way latency = hardware RX timestamp (PC2 PHC) - hardware TX timestamp
(PC1 PHC), joined on the sequence number carried in the frame. Both PHCs are
disciplined by gPTP to the same grandmaster, so the difference is a true
NIC-to-NIC latency; any residual grandmaster offset shows up as a constant bias,
not as jitter.

Usage:
    python3 analyze_plot.py /path/to/results/<run-id>
    python3 analyze_plot.py /path/to/results/<run-id> --show-timeseries
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.ticker import FuncFormatter  # noqa: E402
import matplotlib.patheffects as pe  # noqa: E402

# --- design tokens ---------------------------------------------------------
# Two categorical slots from the validated reference palette (blue, orange).
# Validated: adjacent CVD dE 24.7, normal-vision dE 33.6, contrast >= 3:1.
SERIES = {
    "none":  {"color": "#2a78d6", "label": "No-QoS (PCP 0)",      "marker": "o"},
    "dot1p": {"color": "#eb6834", "label": "IEEE 802.1p (PCP 6)", "marker": "s"},
}
INK_PRIMARY = "#0b0b0b"
INK_SECONDARY = "#52514e"
INK_MUTED = "#8a8984"

# A 2px surface-coloured halo keeps direct labels legible where they cross a mark.
HALO = [pe.withStroke(linewidth=3, foreground="#fcfcfb")]
SURFACE = "#fcfcfb"
GRID = "#e3e2dd"

plt.rcParams.update({
    "figure.facecolor": SURFACE,
    "axes.facecolor": SURFACE,
    "savefig.facecolor": SURFACE,
    "axes.edgecolor": GRID,
    "axes.labelcolor": INK_SECONDARY,
    "axes.titlecolor": INK_PRIMARY,
    "axes.titlesize": 12,
    "axes.titleweight": "semibold",
    "axes.titlelocation": "left",
    "axes.titlepad": 24,
    "axes.labelsize": 10,
    "axes.grid": True,
    "axes.axisbelow": True,
    "grid.color": GRID,
    "grid.linewidth": 0.8,
    "xtick.color": INK_MUTED,
    "ytick.color": INK_MUTED,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.frameon": False,
    "legend.fontsize": 9,
    "legend.labelcolor": INK_SECONDARY,
    "lines.linewidth": 2.0,
    "lines.markersize": 5,
    "font.family": "DejaVu Sans",
    "figure.dpi": 150,
})


# Set by main() when the results directory carries a SYNTHETIC marker file.
# When true, every figure is stamped so a fixture can never be mistaken for a
# measurement - by a reader, or by a future session picking up these files.
SYNTHETIC = False
SYNTHETIC_NOTE = ""


def stamp_synthetic(fig):
    """Diagonal watermark across the whole figure."""
    if not SYNTHETIC:
        return
    fig.text(0.5, 0.5, "SYNTHETIC FIXTURE\nNOT MEASURED DATA",
             fontsize=30, color="#e34948", alpha=0.22, rotation=27,
             ha="center", va="center", zorder=1000,
             fontweight="bold", linespacing=1.4)
    fig.text(0.5, 0.005, "Generated by make_fixture.py - these numbers were "
                         "produced by a random number generator, not by any network.",
             fontsize=7.5, color="#e34948", ha="center", va="bottom", zorder=1000)


def save_fig(fig, out, name):
    stamp_synthetic(fig)
    fig.savefig(out / f"{name}.png", bbox_inches="tight")
    fig.savefig(out / f"{name}.pdf", bbox_inches="tight")
    plt.close(fig)


def despine(ax, keep=("left", "bottom")):
    for side in ("top", "right", "left", "bottom"):
        ax.spines[side].set_visible(side in keep)
    ax.spines["left"].set_color(GRID)
    ax.spines["bottom"].set_color(GRID)


def us_fmt(v, _pos=None):
    return f"{v:,.0f}"


# --- loading ---------------------------------------------------------------
def load_case(case_dir: Path) -> dict | None:
    """Join one measurement point's TX and RX CSVs into a latency series."""
    tx_p, rx_p, meta_p = case_dir / "tx.csv", case_dir / "rx.csv", case_dir / "meta.json"
    if not (tx_p.exists() and rx_p.exists()):
        print(f"  ! {case_dir.name}: missing tx.csv or rx.csv - skipped", file=sys.stderr)
        return None

    meta = json.loads(meta_p.read_text()) if meta_p.exists() else {}
    tx = pd.read_csv(tx_p)
    rx = pd.read_csv(rx_p)
    if tx.empty or rx.empty:
        print(f"  ! {case_dir.name}: empty capture - skipped", file=sys.stderr)
        return None

    # Duplicate sequence numbers should not happen; keep the first if they do.
    tx = tx.drop_duplicates(subset="seq", keep="first")
    rx = rx.drop_duplicates(subset="seq", keep="first")

    df = tx.merge(rx, on="seq", how="inner", suffixes=("_tx", "_rx"))
    df["latency_ns"] = df["rx_hw_ns"].astype("int64") - df["tx_hw_ns"].astype("int64")
    df = df.sort_values("seq").reset_index(drop=True)

    # Drop the first and last 5% - link training, iperf3 ramp-up/tear-down.
    n = len(df)
    if n > 200:
        lo, hi = int(n * 0.05), int(n * 0.95)
        df = df.iloc[lo:hi].reset_index(drop=True)

    sw_used = False
    for col in ("ts_src_tx", "ts_src_rx", "ts_src"):
        if col in df.columns and (df[col] == "sw").any():
            sw_used = True

    return {
        "dir": case_dir,
        "meta": meta,
        "qos": meta.get("qos_mode", case_dir.name.split("_")[0]),
        "load": int(meta.get("background_load_percent", case_dir.name.split("load")[-1] or 0)),
        # len(tx) is the number of recovered TX timestamps, not the number of
        # frames sent. They differ whenever the NIC does not return a timestamp
        # for every frame, and using the former as the loss denominator can
        # produce a negative loss. tsn_tx's own count is carried in meta.json
        # as frames_sent; fall back to the timestamp count only for older runs
        # that predate that field.
        "tx_n": len(tx),
        "sent_n": int(meta.get("frames_sent") or 0) or len(tx),
        "rx_n": len(rx),
        "matched": len(df),
        "latency_us": df["latency_ns"].to_numpy() / 1000.0,
        "seq": df["seq"].to_numpy(),
        "software_timestamps": sw_used,
    }


def summarise(case: dict) -> dict:
    lat = case["latency_us"]
    ipdv = np.diff(lat) if len(lat) > 1 else np.array([0.0])
    sent = case["sent_n"]
    loss = 100.0 * (1.0 - case["rx_n"] / sent) if sent else float("nan")
    return {
        "qos_mode": case["qos"],
        "series": SERIES.get(case["qos"], {}).get("label", case["qos"]),
        "background_load_pct": case["load"],
        "frames_sent": sent,
        "tx_timestamps": case["tx_n"],
        "tx_ts_yield_pct": round(100.0 * case["tx_n"] / sent, 4) if sent else float("nan"),
        "frames_received": case["rx_n"],
        "frames_matched": case["matched"],
        "loss_pct": round(loss, 4),
        "lat_min_us": round(float(np.min(lat)), 3),
        "lat_mean_us": round(float(np.mean(lat)), 3),
        "lat_median_us": round(float(np.median(lat)), 3),
        "lat_p99_us": round(float(np.percentile(lat, 99)), 3),
        "lat_p999_us": round(float(np.percentile(lat, 99.9)), 3),
        "lat_max_us": round(float(np.max(lat)), 3),
        "lat_std_us": round(float(np.std(lat)), 3),
        "ipdv_p99_abs_us": round(float(np.percentile(np.abs(ipdv), 99)), 3),
        "software_timestamps": case["software_timestamps"],
    }


# --- figures ---------------------------------------------------------------
def fig_latency_vs_load(cases, out: Path):
    """Headline: how each QoS mode holds up as the shared link fills."""
    fig, ax = plt.subplots(figsize=(7.6, 4.4))
    for qos, style in SERIES.items():
        sel = sorted([c for c in cases if c["qos"] == qos], key=lambda c: c["load"])
        if not sel:
            continue
        loads = [c["load"] for c in sel]
        med = [float(np.median(c["latency_us"])) for c in sel]
        p99 = [float(np.percentile(c["latency_us"], 99)) for c in sel]
        ax.fill_between(loads, med, p99, color=style["color"], alpha=0.14, linewidth=0)
        ax.plot(loads, p99, color=style["color"], linewidth=1.2, linestyle=(0, (4, 3)), alpha=0.9)
        ax.plot(loads, med, color=style["color"], marker=style["marker"],
                label=style["label"], markeredgecolor=SURFACE, markeredgewidth=1.5)
        # direct label at the right end, so identity is never colour-alone
        ax.annotate(style["label"], xy=(loads[-1], med[-1]), xytext=(6, 0),
                    textcoords="offset points", va="center", fontsize=9,
                    color=INK_SECONDARY, path_effects=HALO)

    ax.set_title("One-way latency vs. background load on the shared inter-switch link")
    ax.set_xlabel("Background load on second port pair (% of link rate)")
    ax.set_ylabel("One-way latency (µs)")
    ax.yaxis.set_major_formatter(FuncFormatter(us_fmt))
    ax.text(0.0, 1.012, "solid = median · dashed = 99th percentile · band = median…p99",
            transform=ax.transAxes, fontsize=8.5, color=INK_MUTED, va="bottom")
    ax.legend(loc="upper left")
    despine(ax)
    fig.tight_layout()
    save_fig(fig, out, "01_latency_vs_load")


def fig_cdf(cases, out: Path):
    """CDF at the heaviest load - where the two configurations diverge most."""
    if not cases:
        return
    top = max(c["load"] for c in cases)
    fig, ax = plt.subplots(figsize=(7.6, 4.4))
    # Direct labels are anchored at different probability levels so the two
    # curves, which sit close together at the low-latency end, never collide.
    label_levels = [0.78, 0.32]
    for (qos, style), level in zip(SERIES.items(), label_levels):
        sel = [c for c in cases if c["qos"] == qos and c["load"] == top]
        if not sel:
            continue
        lat = np.sort(sel[0]["latency_us"])
        y = np.arange(1, len(lat) + 1) / len(lat)
        ax.plot(lat, y, color=style["color"], label=style["label"])
        ax.annotate(style["label"],
                    xy=(float(np.quantile(lat, level)), level), xytext=(12, -2),
                    textcoords="offset points", ha="left", va="center",
                    fontsize=9, color=INK_SECONDARY, path_effects=HALO)
    ax.set_title(f"Latency distribution at {top}% background load")
    ax.set_xlabel("One-way latency (µs)")
    ax.set_ylabel("Cumulative probability")
    ax.set_ylim(0, 1.02)
    ax.axhline(0.99, color=INK_MUTED, linewidth=0.8, linestyle=(0, (2, 3)))
    ax.annotate("p99", xy=(ax.get_xlim()[0], 0.99), xytext=(2, 4),
                textcoords="offset points", fontsize=8, color=INK_MUTED)
    ax.legend(loc="lower right")
    despine(ax)
    fig.tight_layout()
    save_fig(fig, out, "02_latency_cdf")


def fig_box(cases, out: Path):
    """Per-load spread, the closest analogue of the paper's box plots."""
    loads = sorted({c["load"] for c in cases})
    if not loads:
        return
    fig, ax = plt.subplots(figsize=(8.2, 4.4))
    width = 0.34
    handles = []
    for i, (qos, style) in enumerate(SERIES.items()):
        data, pos = [], []
        for j, load in enumerate(loads):
            sel = [c for c in cases if c["qos"] == qos and c["load"] == load]
            if not sel:
                continue
            data.append(sel[0]["latency_us"])
            pos.append(j + (i - 0.5) * width)
        if not data:
            continue
        bp = ax.boxplot(data, positions=pos, widths=width * 0.86, patch_artist=True,
                        showfliers=False, whis=(1, 99), manage_ticks=False)
        for patch in bp["boxes"]:
            patch.set_facecolor(style["color"])
            patch.set_alpha(0.28)
            patch.set_edgecolor(style["color"])
            patch.set_linewidth(1.4)
        for key in ("whiskers", "caps"):
            for item in bp[key]:
                item.set_color(style["color"])
                item.set_linewidth(1.2)
        for med in bp["medians"]:
            med.set_color(style["color"])
            med.set_linewidth(2.0)
        handles.append(plt.Line2D([], [], color=style["color"], linewidth=6,
                                  alpha=0.5, label=style["label"]))

    ax.set_xticks(range(len(loads)))
    ax.set_xticklabels([f"{l}%" for l in loads])
    ax.set_title("One-way latency spread by background load")
    ax.set_xlabel("Background load on second port pair")
    ax.set_ylabel("One-way latency (µs)")
    ax.yaxis.set_major_formatter(FuncFormatter(us_fmt))
    ax.text(0.0, 1.012, "box = quartiles · whiskers = 1st…99th percentile",
            transform=ax.transAxes, fontsize=8.5, color=INK_MUTED, va="bottom")
    ax.legend(handles=handles, loc="upper left")
    despine(ax)
    fig.tight_layout()
    save_fig(fig, out, "03_latency_box")


def fig_loss(cases, out: Path):
    loads = sorted({c["load"] for c in cases})
    fig, ax = plt.subplots(figsize=(7.6, 3.8))
    width = 0.36
    any_loss = False
    for i, (qos, style) in enumerate(SERIES.items()):
        xs, ys = [], []
        for j, load in enumerate(loads):
            sel = [c for c in cases if c["qos"] == qos and c["load"] == load]
            if not sel:
                continue
            loss = 100.0 * (1.0 - sel[0]["rx_n"] / sel[0]["tx_n"]) if sel[0]["tx_n"] else 0.0
            loss = max(loss, 0.0)
            any_loss |= loss > 0.001
            xs.append(j + (i - 0.5) * width)
            ys.append(loss)
        bars = ax.bar(xs, ys, width=width * 0.9, color=style["color"], label=style["label"],
                      edgecolor=SURFACE, linewidth=2)
        for rect, val in zip(bars, ys):
            if val > 0.001:
                ax.annotate(f"{val:.2f}%", xy=(rect.get_x() + rect.get_width() / 2, val),
                            xytext=(0, 3), textcoords="offset points",
                            ha="center", fontsize=8, color=INK_SECONDARY)
    ax.set_xticks(range(len(loads)))
    ax.set_xticklabels([f"{l}%" for l in loads])
    ax.set_title("Frame loss of the measured stream")
    ax.set_xlabel("Background load on second port pair")
    ax.set_ylabel("Loss (%)")
    if not any_loss:
        ax.text(0.5, 0.5, "no frame loss in any configuration",
                transform=ax.transAxes, ha="center", va="center",
                fontsize=11, color=INK_MUTED)
    ax.legend(loc="upper left")
    despine(ax)
    fig.tight_layout()
    save_fig(fig, out, "04_frame_loss")


def fig_timeseries(cases, out: Path):
    """Diagnostic: latency over the run at the heaviest load."""
    if not cases:
        return
    top = max(c["load"] for c in cases)
    fig, axes = plt.subplots(2, 1, figsize=(7.6, 5.2), sharex=True, sharey=True)
    plotted = False
    for ax, (qos, style) in zip(axes, SERIES.items()):
        sel = [c for c in cases if c["qos"] == qos and c["load"] == top]
        if not sel:
            ax.set_visible(False)
            continue
        c = sel[0]
        ax.plot(c["seq"], c["latency_us"], color=style["color"], linewidth=0.7, alpha=0.85)
        ax.set_title(style["label"], fontsize=10)
        ax.set_ylabel("Latency (µs)")
        despine(ax)
        plotted = True
    if not plotted:
        plt.close(fig)
        return
    axes[-1].set_xlabel("Frame sequence number")
    fig.suptitle(f"Per-frame latency at {top}% background load", x=0.02, ha="left",
                 fontsize=12, fontweight="semibold", color=INK_PRIMARY)
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    save_fig(fig, out, "05_latency_timeseries")


# --- main ------------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("results", type=Path, help="results/<run-id> directory")
    ap.add_argument("--no-timeseries", action="store_true")
    args = ap.parse_args()

    root: Path = args.results
    if not root.is_dir():
        print(f"not a directory: {root}", file=sys.stderr)
        return 2

    # A SYNTHETIC marker means this directory holds fabricated fixture data.
    # run_measurement.sh never writes it; make_fixture.py always does.
    global SYNTHETIC, SYNTHETIC_NOTE
    marker = root / "SYNTHETIC"
    if marker.exists():
        SYNTHETIC = True
        SYNTHETIC_NOTE = marker.read_text().strip()
        print("=" * 78, file=sys.stderr)
        print("!! SYNTHETIC FIXTURE DATA - these are NOT measurements.", file=sys.stderr)
        print("!! Every figure will be watermarked. Do not publish or cite these numbers.",
              file=sys.stderr)
        print("=" * 78, file=sys.stderr)

    case_dirs = sorted(d for d in root.iterdir() if d.is_dir() and d.name != "figures")
    print(f"loading {len(case_dirs)} measurement points from {root}")
    cases = [c for c in (load_case(d) for d in case_dirs) if c]
    if not cases:
        print("no usable measurement points found", file=sys.stderr)
        return 1

    rows = [summarise(c) for c in cases]
    summary = pd.DataFrame(rows).sort_values(["qos_mode", "background_load_pct"])
    summary.insert(0, "data_source", "SYNTHETIC_FIXTURE" if SYNTHETIC else "measured")
    summary.to_csv(root / "summary.csv", index=False)

    figures = root / "figures"
    figures.mkdir(exist_ok=True)
    fig_latency_vs_load(cases, figures)
    fig_cdf(cases, figures)
    fig_box(cases, figures)
    fig_loss(cases, figures)
    if not args.no_timeseries:
        fig_timeseries(cases, figures)

    # markdown summary, easy to paste into a report
    cols = ["series", "background_load_pct", "frames_sent", "frames_received", "loss_pct",
            "tx_ts_yield_pct",
            "lat_median_us", "lat_p99_us", "lat_max_us", "lat_std_us"]
    title = ("# TSN-FlexTest (I226 adaptation) - SYNTHETIC FIXTURE, NOT MEASURED DATA"
             if SYNTHETIC else
             "# TSN-FlexTest (I226 adaptation) - measurement summary")
    md = [title, ""]
    if SYNTHETIC:
        md += ["> **These numbers were produced by a random number generator, not by any",
               "> network.** They exist only to exercise the analysis code. Do not publish,",
               "> cite, or compare them against real results.", ""]
        if SYNTHETIC_NOTE:
            md += ["```", SYNTHETIC_NOTE, "```", ""]
    md += [f"Run: `{root.name}`", ""]
    md.append(summary[cols].to_markdown(index=False))
    if summary["software_timestamps"].any():
        md += ["", "> **Warning:** at least one measurement point fell back to software "
                   "timestamps. Those numbers include host-stack jitter and are not "
                   "NIC-to-NIC latencies."]
    (root / "summary.md").write_text("\n".join(md) + "\n")

    print(summary[cols].to_string(index=False))
    print(f"\nfigures -> {figures}")
    print(f"summary -> {root / 'summary.csv'}, {root / 'summary.md'}")
    if SYNTHETIC:
        print("\nREMINDER: this run is SYNTHETIC FIXTURE DATA, not a measurement.",
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
